using System.Collections.Generic;
using Bari.Core.Generic;
using Bari.Core.Model;

namespace Bari.Plugins.PythonScripts.Scripting
{
    public interface IProjectBuildScriptRunner
    {
        /// <summary>
        /// Executes the given build script on the given project, returning the set of
        /// target files the script generated.
        /// </summary>
        /// <param name="project">The input project to build</param>
        /// <param name="buildScript">The build script to execute</param>
        /// <returns>Returns the set of files generated by the script. They have to be
        /// indicated in the script's <c>results</c> variable.</returns>
        ISet<TargetRelativePath> Run(Project project, IBuildScript buildScript);
    }
}